name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Dependency
        run: sudo apt install wine64

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - run: yarn

      - name: Build All Platforms
        run: yarn make

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_name: ilbe-ports ${{ github.ref }}
          tag_name: ${{ github.ref }}
          draft: false
          prerelease: true

      - name: Upload Ubuntu Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./out/ubuntu.deb
          asset_name: ilbecon-ports_${{ github.ref }}_amd64.deb
          asset_content_type: application/deb

      - name: Upload Fedora Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./out/fedora.rpm
          asset_name: ilbecon-ports-${{ github.ref }}-1.x86_64.rpm
          asset_content_type: application/rpm

      - name: Upload Windows Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./out/windows.zip
          asset_name: ilbecon-ports-win32-x64-${{ github.ref }}.zip
          asset_content_type: application/zip

      - name: Upload MacOS Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./out/macos.zip
          asset_name: ilbecon-ports-darwin-x64-${{ github.ref }}.zip
          asset_content_type: application/zip
